name: build-master-branch

on:
  push:
    branches: [ devel ]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      GITHUB_CI: true

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build
        run: ./.ci/build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: master
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_dir: ./master_output
          allow_empty_commit: true
          force_orphan: true
