name: CI

on:
  push:
    branches: [ devel ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ devel ]

  workflow_dispatch:

jobs:

  cancel:

    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  docs:
    runs-on: ubuntu-20.04
    env:
      GITHUB_CI: true
    steps:

      - uses: actions/checkout@v2

      - name: Build
        run: ./.ci/build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./master_output
          allow_empty_commit: true
          force_orphan: true
